apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: extreme-storage
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: hyperdisk-extreme
  provisioned-iops-on-create: '9000'
