apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: postgres-operator
  name: postgres-operator
  namespace: cpo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        cpo.cybertec.at/pod-type: postgres-operator
        name: postgres-operator
    spec:
      containers:
      - env:
        - name: POSTGRES_OPERATOR_CONFIGURATION_OBJECT
          value: postgresql-operator-configuration
        image: docker.io/cybertecpostgresql/cybertec-pg-operator:v0.7.0-rc7-x86_64
        imagePullPolicy: Always
        name: postgres-operator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cpo-operator
      serviceAccountName: cpo-operator
      terminationGracePeriodSeconds: 30
